# Generated by Django 3.2.7 on 2021-09-05 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0002_remove_profile_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='status',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
