# Generated by Django 3.2.7 on 2021-09-13 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0004_file_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='text',
            field=models.TextField(default='{}'),
            preserve_default=False,
        ),
    ]
