# Generated by Django 3.2.7 on 2021-09-20 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0005_profile_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='text',
            new_name='definition',
        ),
    ]
