# Generated by Django 3.2.7 on 2021-09-20 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0006_rename_text_profile_definition'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='fps',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='file',
            name='progress',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
