# Generated by Django 3.2.7 on 2021-09-20 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0007_auto_20210920_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='completion_datetime',
            field=models.DateTimeField(default="1970-01-01 00:00:00Z"),
        ),
        migrations.AddField(
            model_name='file',
            name='creation_datetime',
            field=models.DateTimeField(default="1970-01-01 00:00:00Z"),
        ),
    ]
