# Generated by Django 3.2.7 on 2021-09-20 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0008_auto_20210920_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='eta',
            field=models.IntegerField(default=-1),
        ),
    ]
