# Generated by Django 3.2.7 on 2022-01-23 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0012_file_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='frame_count',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
