# Generated by Django 3.2.7 on 2022-01-23 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0013_file_frame_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='fps',
            new_name='encode_fps',
        ),
    ]
