# Generated by Django 3.2.7 on 2022-01-23 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0014_rename_fps_file_encode_fps'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='frame_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
