# Generated by Django 3.2.7 on 2022-01-23 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0015_file_frame_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='frame_rate',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=6),
        ),
    ]
