# Generated by Django 3.2.7 on 2022-03-20 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0016_alter_file_frame_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='frame_count',
        ),
    ]
