# Generated by Django 3.2.7 on 2022-04-18 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0017_remove_file_frame_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='definition',
        ),
        migrations.AddField(
            model_name='file',
            name='encode_type',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='file',
            name='encode_value',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='profile',
            name='base_crf',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='encoder',
            field=models.TextField(default='libx264'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='main_audio_compatibility',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='secondary_audio_compatibility',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
