# Generated by Django 3.2.7 on 2022-04-18 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0018_auto_20220417_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='base_crf',
        ),
        migrations.AddField(
            model_name='profile',
            name='encode_type',
            field=models.CharField(default='crf', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='encode_value',
            field=models.IntegerField(default=18),
            preserve_default=False,
        ),
    ]
