# Generated by Django 3.2.7 on 2022-04-18 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0019_auto_20220417_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='encoder_tune',
            field=models.TextField(blank=True),
        ),
    ]
