# Generated by Django 3.2.7 on 2022-04-18 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0020_profile_encoder_tune'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='keep_original_main_audio',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='keep_original_secondary_audio',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
