# Generated by Django 3.2.7 on 2022-04-20 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0021_auto_20220418_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='encoder_preset',
            field=models.CharField(default='slow', max_length=16),
            preserve_default=False,
        ),
    ]
