# Generated by Django 4.1.4 on 2023-01-14 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0022_profile_encoder_preset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='creation_datetime',
        ),
        migrations.RemoveField(
            model_name='file',
            name='encode_end_datetime',
        ),
        migrations.RemoveField(
            model_name='file',
            name='encode_fps',
        ),
        migrations.RemoveField(
            model_name='file',
            name='encode_start_datetime',
        ),
        migrations.RemoveField(
            model_name='file',
            name='encode_type',
        ),
        migrations.RemoveField(
            model_name='file',
            name='encode_value',
        ),
        migrations.RemoveField(
            model_name='file',
            name='eta',
        ),
        migrations.RemoveField(
            model_name='file',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='file',
            name='progress',
        ),
        migrations.RemoveField(
            model_name='file',
            name='status',
        ),
        migrations.RemoveField(
            model_name='file',
            name='worker',
        ),
        migrations.AddField(
            model_name='file',
            name='frames',
            field=models.IntegerField(default=-1),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
