# Generated by Django 4.1.4 on 2023-01-14 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0023_remove_file_creation_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='hash',
            field=models.CharField(default='0', max_length=40),
            preserve_default=False,
        ),
    ]
