# Generated by Django 4.1.4 on 2023-01-17 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0026_file_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='duration',
            field=models.DecimalField(decimal_places=3, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='frame_rate',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='frames',
            field=models.IntegerField(null=True),
        ),
    ]
