# Generated by Django 4.1.4 on 2023-03-11 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0027_alter_file_duration_alter_file_frame_rate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='path',
            new_name='directory',
        ),
    ]
