# Generated by Django 4.1.7 on 2023-03-25 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0029_alter_file_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='hash',
        ),
    ]
