# Generated by Django 4.2.7 on 2024-05-25 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0031_file_ffprobe_information'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='ffprobe_information',
        ),
    ]
