# Generated by Django 4.1.4 on 2023-01-14 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('distributor', '0023_remove_file_creation_datetime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True)),
                ('encoder', models.TextField()),
                ('encode_type', models.CharField(max_length=3)),
                ('encode_value', models.IntegerField()),
                ('encoder_preset', models.CharField(max_length=16)),
                ('encoder_tune', models.TextField(blank=True)),
                ('keep_original_main_audio', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='EncodeTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker', models.CharField(blank=True, max_length=128)),
                ('encode_type', models.CharField(blank=True, max_length=3)),
                ('encode_value', models.IntegerField(default=-1)),
                ('status', models.TextField()),
                ('progress', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('encode_framerate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('seconds_remaining', models.IntegerField(default=-1)),
                ('creation_datetime', models.DateTimeField(default='1970-01-01 00:00:00Z')),
                ('encode_start_datetime', models.DateTimeField(default='1970-01-01 00:00:00Z')),
                ('encode_end_datetime', models.DateTimeField(default='1970-01-01 00:00:00Z')),
                ('compressed_file', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_compressed_related', related_query_name='%(app_label)s_%(class)s_compressed_files', to='distributor.file')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encodes.profile')),
                ('source_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_source_related', related_query_name='%(app_label)s_%(class)s_source_files', to='distributor.file')),
            ],
        ),
    ]
