# Generated by Django 4.1.4 on 2023-01-14 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encodes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='encodetask',
            options={'verbose_name': 'Encode Task'},
        ),
        migrations.AlterField(
            model_name='encodetask',
            name='creation_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='encodetask',
            name='encode_end_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='encodetask',
            name='encode_start_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
