# Generated by Django 4.1.4 on 2023-01-14 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encodes', '0003_alter_encodetask_encode_framerate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='additional_arguments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='encodetask',
            name='status',
            field=models.IntegerField(choices=[(0, 'Created'), (1, 'Queued'), (2, 'Downloading'), (3, 'In Progress'), (4, 'Uploading'), (5, 'Complete')], default=0),
        ),
    ]
