# Generated by Django 4.1.4 on 2023-03-11 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encodes', '0005_alter_profile_additional_arguments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='additional_arguments',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='encoder_tune',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
