# Generated by Django 4.2 on 2023-11-21 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encodes', '0006_alter_profile_additional_arguments_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='encoder',
            new_name='codec',
        ),
    ]
