# Generated by Django 4.1.4 on 2023-01-14 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('distributor', '0023_remove_file_creation_datetime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psnr', models.BooleanField(default=True)),
                ('ms_ssim', models.BooleanField(default=True)),
                ('vmaf', models.BooleanField(default=True)),
                ('neg_mode', models.BooleanField(default=True)),
                ('subsample_rate', models.IntegerField(default=1)),
                ('worker', models.CharField(blank=True, max_length=128)),
                ('status', models.TextField()),
                ('progress', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('processing_framerate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('seconds_remaining', models.IntegerField(default=-1)),
                ('creation_datetime', models.DateTimeField(default='1970-01-01 00:00:00Z')),
                ('encode_start_datetime', models.DateTimeField(null=True)),
                ('encode_end_datetime', models.DateTimeField(null=True)),
                ('compressed_file', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_compressed_related', related_query_name='%(app_label)s_%(class)s_compressed_files', to='distributor.file')),
                ('source_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_source_related', related_query_name='%(app_label)s_%(class)s_source_files', to='distributor.file')),
            ],
        ),
        migrations.CreateModel(
            name='PooledVMAF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min', models.DecimalField(decimal_places=6, max_digits=9)),
                ('max', models.DecimalField(decimal_places=6, max_digits=9)),
                ('mean', models.DecimalField(decimal_places=6, max_digits=9)),
                ('harmonic_mean', models.DecimalField(decimal_places=6, max_digits=9)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metrics.metrictask')),
            ],
        ),
        migrations.CreateModel(
            name='PooledPSNR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min', models.DecimalField(decimal_places=6, max_digits=8)),
                ('max', models.DecimalField(decimal_places=6, max_digits=8)),
                ('mean', models.DecimalField(decimal_places=6, max_digits=8)),
                ('harmonic_mean', models.DecimalField(decimal_places=6, max_digits=8)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metrics.metrictask')),
            ],
        ),
        migrations.CreateModel(
            name='PooledMSSSIM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min', models.DecimalField(decimal_places=6, max_digits=7)),
                ('max', models.DecimalField(decimal_places=6, max_digits=7)),
                ('mean', models.DecimalField(decimal_places=6, max_digits=7)),
                ('harmonic_mean', models.DecimalField(decimal_places=6, max_digits=7)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metrics.metrictask')),
            ],
        ),
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_number', models.IntegerField()),
                ('psnr', models.DecimalField(decimal_places=6, max_digits=8, null=True)),
                ('ms_ssim', models.DecimalField(decimal_places=6, max_digits=7, null=True)),
                ('vmaf', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metrics.metrictask')),
            ],
        ),
    ]
