# Generated by Django 4.1.4 on 2023-01-14 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metrictask',
            options={'verbose_name': 'Metric Task'},
        ),
        migrations.AlterModelOptions(
            name='pooledmsssim',
            options={'verbose_name': 'Pooled MS_SSIM Metric'},
        ),
        migrations.AlterModelOptions(
            name='pooledpsnr',
            options={'verbose_name': 'Pooled PSNR Metric'},
        ),
        migrations.AlterModelOptions(
            name='pooledvmaf',
            options={'verbose_name': 'Pooled VMAF Metric'},
        ),
        migrations.AlterField(
            model_name='metrictask',
            name='creation_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
