# Generated by Django 4.2.7 on 2024-05-25 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0004_rename_encode_end_datetime_metrictask_analyze_end_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pooledmsssim',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='metrics.metrictask'),
        ),
        migrations.AlterField(
            model_name='pooledpsnr',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='metrics.metrictask'),
        ),
        migrations.AlterField(
            model_name='pooledvmaf',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='metrics.metrictask'),
        ),
    ]
